-- РАСШИРЕНИЕ FAQ ДЛЯ 7 ЯЗЫКОВ
ALTER TABLE faq ADD COLUMN IF NOT EXISTS topic_en TEXT;
ALTER TABLE faq ADD COLUMN IF NOT EXISTS content_en TEXT;

ALTER TABLE faq ADD COLUMN IF NOT EXISTS topic_tr TEXT;
ALTER TABLE faq ADD COLUMN IF NOT EXISTS content_tr TEXT;

ALTER TABLE faq ADD COLUMN IF NOT EXISTS topic_de TEXT;
ALTER TABLE faq ADD COLUMN IF NOT EXISTS content_de TEXT;

ALTER TABLE faq ADD COLUMN IF NOT EXISTS topic_pl TEXT;
ALTER TABLE faq ADD COLUMN IF NOT EXISTS content_pl TEXT;

ALTER TABLE faq ADD COLUMN IF NOT EXISTS topic_ar TEXT;
ALTER TABLE faq ADD COLUMN IF NOT EXISTS content_ar TEXT;

ALTER TABLE faq ADD COLUMN IF NOT EXISTS topic_fa TEXT;
ALTER TABLE faq ADD COLUMN IF NOT EXISTS content_fa TEXT;
